version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "calculator"
    # server:
    #   build: ./server
    #   ports:
    #     - "3000:3000"
    #   environment:
    #     DATABASE_URL: "postgresql://postgres:postgres@db:5432/calculator"